# To set up SonarCloud, update the properties below with your project details

sonar.projectKey=DEFRA_ai-assure-frontend
sonar.organization=defra

sonar.links.homepage=https://github.com/atanu-cts/ai-assure-frontend
sonar.links.ci=https://github.com/DEFRA/cdp-node-frontend-template/actions
sonar.links.scm=https://github.com/DEFRA/cdp-node-frontend-template
sonar.links.issue=https://github.com/DEFRA/cdp-node-frontend-template/issues

sonar.sources=src/
sonar.exclusions=src/**/*.test.js
sonar.tests=src/
sonar.test.inclusions=src/**/*.test.js

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.cpd.exclusions=src/**/*.test.js
